# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific aliases and functions
            
alias lo="exit"
alias ls="ls -F"
alias more="less"
alias rm="rm -i"
alias ssh="ssh -o VisualHostKey=yes"
alias vi='vim'

set -o vi

#rvm use 1.9.3-p551@
