#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# Modules from github
mod 'puppetlabs/aws',
    :git => 'git://github.com/puppetlabs/puppetlabs-aws'

mod 'camptocamp/accounts',
    :git => 'git://github.com/camptocamp/puppet-accounts'

mod 'puppetlabs/apache',
    :git => 'git://github.com/puppetlabs/puppetlabs-apache'

mod 'camptocamp/archive',
    :git => 'git://github.com/camptocamp/puppet-archive'

mod 'camptocamp/augeas',
    :git => 'git://github.com/camptocamp/puppet-augeas'

mod 'herculesteam/augeasproviders_core',
    :git => 'git://github.com/hercules-team/augeasproviders_core'

mod 'herculesteam/augeasproviders_base',
    :git => 'git://github.com/hercules-team/augeasproviders_base'

mod 'puppetlabs/concat',
    :git => 'git://github.com/puppetlabs/puppetlabs-concat'

mod 'stahnma/epel', 
    :git => 'git://github.com/stahnma/puppet-module-epel'

mod 'puppetlabs/inifile',
    :git => 'git://github.com/puppetlabs/puppetlabs-inifile'

mod 'hunner/hiera',
    :git => 'https://github.com/hunner/puppet-hiera.git'

mod 'puppetlabs/java',
    :git => 'git://github.com/puppetlabs/puppetlabs-java'

mod 'jlbfalcao/jruby',
    :git => 'git://github.com/intelie/puppet-jruby'

mod 'yo61/logrotate',
    :git => 'git://github.com/yo61/puppet-logrotate'

mod 'puppetlabs/mysql',
    :git => 'git://github.com/puppetlabs/puppetlabs-mysql'

mod 'hubspot/nexus',
    :git => 'git://github.com/hubspotdevops/puppet-nexus'

mod 'glarizza/notifyme',
    :git => 'git://github.com/glarizza/puppet-notifyme.git'

mod 'puppetlabs/ntp',
    :git => 'git://github.com/puppetlabs/puppetlabs-ntp'

mod 'example42/puppi',
    :git => 'git://github.com/example42/puppi'

mod 'stankevich/python',
    :git => 'git://github.com/stankevich/puppet-python'

mod 'zack/r10k',
    :git => 'git://github.com/acidprime/r10k'

mod 'jdowning/rbenv',
    :git => 'git://github.com/justindowning/puppet-rbenv'

mod 'maestrodev/rvm',
   :git => 'git://github.com/maestrodev/puppet-rvm'

mod 'golja/s3cmd',
    :git => 'git://github.com/n1tr0g/golja-s3cmd'

mod 'puppetlabs/stdlib',
    :git => 'git://github.com/puppetlabs/puppetlabs-stdlib'

mod 'puppetlabs/vcsrepo',
    :git => 'git://github.com/puppetlabs/puppetlabs-vcsrepo'

mod 'maestrodev/wget',
    :git => 'git://github.com/maestrodev/puppet-wget'

mod 'aco/yum_autoupdate',
    :git => 'git://github.com/antoineco/aco-yum_autoupdate'
#    #:ref => '0.6.2'


mod 'flannon/archivesspace',
    :git => 'git://github.com/flannon/puppet-archivesspace.git'
    #:ref => 'master'

#mod 'flannon/archivesspace_dev',
#    :git => 'git://github.com/flannon/puppet-archivesspace_dev.git',
#    :ref => 'master'

mod 'rtyler-jenkins',
    :git => 'https://github.com/jenkinsci/puppet-jenkins.git',
    :ref => 'release-1.6.x'

mod 'puppetlabs/firewall',
    :git => 'git://github.com/puppetlabs/puppetlabs-firewall.git'
#    :ref => '1.7.1'

mod 'Sliim/pyenv',
    :git => 'git://github.com/Sliim/puppet-pyenv.git'

#mod 'yguenane/repoforge', 
mod 'Mylezeem/repoforge', 
     :git => 'git://github.com/Mylezeem/puppet-repoforge.git'
     #:ref => "0.2.1"

###mod 'puppetlabs-rpmbuilder',
###    :git => "https://github.com/puppetlabs/puppetlabs-rpmbuilder.git"
