#!/usr/bin/env ruby
#^syntax detection

moduledir 'modules/thirdparty'

forge 'https://forgeapi.puppetlabs.com'

# Modules from github
#mod 'puppetlabs/aws',
#    :git => 'git://github.com/puppetlabs/puppetlabs-aws',
#    :tag => '1.0.0'

mod 'camptocamp/accounts',
    :git => 'git://github.com/camptocamp/puppet-accounts',
    :tag => '1.8.1'

mod 'puppetlabs/apache',
    :git => 'git://github.com/puppetlabs/puppetlabs-apache',
    :tag => '1.10.0'

#mod 'camptocamp/archive',
#    :git => 'git://github.com/camptocamp/puppet-archive',
#    :tag => '0.8.2'

#mod 'camptocamp/augeas',
#    :git => 'git://github.com/camptocamp/puppet-augeas',
#    :tag => '1.4.3'

#mod 'herculesteam/augeasproviders_core',
#    :git => 'git://github.com/hercules-team/augeasproviders_core'

#mod 'herculesteam/augeasproviders_base',
#    :git => 'git://github.com/hercules-team/augeasproviders_base'

mod 'puppetlabs/concat',
    :git => 'git://github.com/puppetlabs/puppetlabs-concat',
    :tag => '2.2.0'

mod 'stahnma/epel', 
    :git => 'git://github.com/stahnma/puppet-module-epel',
    :tag => '1.2.2'

mod 'hunner/hiera',
        :git => 'https://github.com/hunner/puppet-hiera.git'

mod 'puppetlabs/inifile',
    :git => 'git://github.com/puppetlabs/puppetlabs-inifile',
    :tag => '1.5.0'

mod 'puppetlabs/java',
    :git => 'git://github.com/puppetlabs/puppetlabs-java',
    :tag => '1.6.0'

#mod 'jlbfalcao/jruby',
#    :git => 'git://github.com/intelie/puppet-jruby'

mod 'yo61/logrotate',
    :git => 'git://github.com/yo61/puppet-logrotate',
    :tag => 'v1.4.0'

mod 'puppetlabs/mysql',
    :git => 'git://github.com/puppetlabs/puppetlabs-mysql',
    :tag => '3.8.0'

mod 'hubspot/nexus',
    :git => 'git://github.com/hubspotdevops/puppet-nexus',
    :tag => '1.6.1'

mod 'glarizza/notifyme',
    :git => 'git://github.com/glarizza/puppet-notifyme.git'

mod 'puppetlabs/ntp',
    :git => 'git://github.com/puppetlabs/puppetlabs-ntp',
    :tag => '4.2.0'

#mod 'example42/puppi',
#    :git => 'git://github.com/example42/puppi'

mod 'stankevich/python',
    :git => 'git://github.com/stankevich/puppet-python',
    :tag => '1.14.0'

mod 'zack/r10k',
    :git => 'git://github.com/acidprime/r10k',
    :tag => 'v3.2.0'

mod 'jdowning/rbenv',
    :git => 'git://github.com/justindowning/puppet-rbenv',
    :tag => '2.1.0'

mod 'maestrodev/rvm',
   :git => 'git://github.com/maestrodev/puppet-rvm',
   :tag => 'v1.13.1'

mod 'golja/s3cmd',
    :git => 'git://github.com/n1tr0g/golja-s3cmd',
    :tag => '0.1.0'

mod 'puppetlabs/stdlib',
    :git => 'git://github.com/puppetlabs/puppetlabs-stdlib',
    :tag => '4.12.0'

mod 'petems/swap_file',
        :git => 'git://github.com/petems/petems-swap_file'
        #:tag => '3.0.2'

mod 'puppetlabs/vcsrepo',
    :git => 'git://github.com/puppetlabs/puppetlabs-vcsrepo',
    :tag => '1.3.2'

#mod 'maestrodev/wget',
#    :git => 'git://github.com/maestrodev/puppet-wget'

mod 'aco/yum_autoupdate',
    :git => 'git://github.com/antoineco/aco-yum_autoupdate',
    :ref => '0.6.2'


mod 'flannon/archivesspace',
    :git => 'git://github.com/flannon/puppet-archivesspace.git',
    :ref => '0.1.4'
    #:ref => 'master'

mod 'flannon/archivesspace_dev',
    :git => 'git://github.com/flannon/puppet-archivesspace_dev.git',
    :ref => 'master'

mod 'rtyler-jenkins',
    :git => 'https://github.com/jenkinsci/puppet-jenkins.git',
    :ref => 'v1.6.1'

##mod 'puppet-community/mysql_java_connector',
##    :git => 'git://github.com/puppet-community/puppet-mysql_java_connector.git'
    
mod 'puppetlabs/firewall',
    :git => 'git://github.com/puppetlabs/puppetlabs-firewall.git',
    :ref => '1.8.1'

mod 'Sliim/pyenv',
    :git => 'git://github.com/Sliim/puppet-pyenv.git',
    :tag => '0.1.1'

mod 'Mylezeem/repoforge', 
     :git => 'git://github.com/Mylezeem/puppet-repoforge.git',
     :ref => "0.2.1"

