# -*- mode: ruby -*-
# vi: set ft=ruby :
#

HOST_NAME = "multidisk"
MEMORY    = "2048"
DISK = './dev/secondDisk.vdi' 
CONTROLLER = "IDE Controller"

Vagrant.configure(2) do |config|
  # Disable insecure key replacement
  config.ssh.insert_key = false
  # Use your id_rsa key from !/.ssh
  config.ssh.private_key_path = [ '~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa' ]
  # Archivesspace available versions
  #config.vm.box = "NYULibraries/archivesspace_1.5.2"
  config.vm.box = "NYULibraries/archivesspace_2.0.0"
  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
		vb.name = HOST_NAME
    vb.memory = MEMORY
    #vb.customize ['createhd', '--filename', disk, '--size', 20 * 1024]
    #vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
		#vb.customize ["storagectl", :id, "--add", "sata", "--name", "SATA" , "--portcount", 2, "--hostiocache", "on"]

		unless File.exist?(DISK)
    	vb.customize ['createhd', '--filename', DISK, '--variant', 'Fixed', '--size', 1 * 1024]
    end
    vb.customize ['storageattach', :id,  '--storagectl', CONTROLLER, '--port', 1, '--device', 0, '--type', 'hdd', '--medium', DISK]
  end
  #config.vm.network "private_network", type: "dhcp",
  config.vm.network "private_network", ip: "192.168.50.39",
      virtualbox__hostonly: true
  config.vm.network "forwarded_port", guest:  8080, host: 8080,
    auto_correct: true
  config.vm.network "forwarded_port", guest:  8081, host: 8081,
    auto_correct: true
  config.vm.network "forwarded_port", guest:  8089, host: 8089,
    auto_correct: true
  config.vm.network "forwarded_port", guest:  8090, host: 8090,
    auto_correct: true
  config.vm.hostname = HOST_NAME + ".local"
  #config.vm.synced_folder "./", "/vagrant", disabled: true
  #config.vm.synced_folder "./", "/vagrant-" + HOST_NAME, id: "vagrant-" + HOST_NAME

end
